### ISSUE TITLE
Scrolling event

### ISSUE THREAD

**Issue by tschaka1904** [dsehnal/LiteMol#18]
I've a request to for the scrolling behaviour of the LiteMol viewer. Currently when you scroll a long a page and courser hovers over the LiteMol viewer I get stuck in the viewer and have to move my mouse out of it. 
![jun-26-2017 14-27-06](https://user-images.githubusercontent.com/5269116/27541359-96e46178-5a7b-11e7-8fda-0b55a98c2fd6.gif)

It would be nice, if the scrolling event only actives if I stop scrolling and stay in the widget. Otherwise, on smaller screens it mights be very difficult to scroll. The guys from Reactome, had a similar problem and as their viewer takes the whole width of the page it was sometimes impossible to scroll.
![jun-26-2017 14-31-46](https://user-images.githubusercontent.com/5269116/27541663-a819fd8a-5a7c-11e7-9744-de71db4b6635.gif)

**Comment by dsehnal** [comment]
Ok, I will make the scrolling active only when the user moves the mouse inside the viewport after the cursor has entered.

**Comment by dsehnal** [comment]
Should be fixed. 

For your UI, I think it might be better if you set the LiteMol background to while (``plugin.setViewportBackground('#fff')``).

**Comment by tschaka1904** [comment]
Thanks, I'll give it a try! 

Already happened in the most recent test version! 👍 
![screen shot 2017-06-26 at 15 24 11](https://user-images.githubusercontent.com/5269116/27543930-8f43a05c-5a83-11e7-8e63-26a81a265df3.png)

**Comment by tschaka1904** [comment]
Seems like we're getting there, but I've the feeling the it takes quite a little bit of time until I'm actually able to use the scroll to play the the LiteMol viewer. Is there a `timeout`?

**Comment by dsehnal** [comment]
No, there is a minimum number of pixels the camera has to move: https://github.com/dsehnal/LiteMol/blob/master/src/lib/Visualization/Base/Camera.ts#L113

Can you please try to tweak the constant to something that feels right for you? You can do it directly in the compiled code by searching for ``mouseMoveDelta`` string.

**Comment by tschaka1904** [comment]
Actually I think it okay! I just had to play with it a bit, as the behaviour is slightly different. Thanks for implementing this feature. 👍

**Comment by dsehnal** [comment]
I reduced it to 15 pixels in the latest version regardless :)

Thanks for the feedback.
