### ISSUE TITLE
White background issue with Safari

### ISSUE THREAD

**Issue by tschaka1904** [dsehnal/LiteMol#19]
Safari Version 9.1 (11601.5.17.1)

Seems to work in Chrome and Firefox, but in Safari I have a black border on two sides of the viewer. It seems to change by width as well. 
![screen shot 2017-06-27 at 10 42 19](https://user-images.githubusercontent.com/5269116/27581397-842fa4a2-5b25-11e7-8066-898fdb087097.png)

As soon as I've deployed a new version of the Complex Portal, I'll share a link to so you can see this in action.

**Comment by dsehnal** [comment]
Are you sure it's not caused by your CSS that you use to position the plugin?

Either way, I will just set the background of the div that wraps the viewport to its background color instead of always using black. I will do it later today.

**Comment by dsehnal** [comment]
The border should now be gone.
