### ISSUE TITLE
TypeError: Cannot read property 'PropTypes' of undefined

### ISSUE THREAD

**Issue by tschaka1904** [dsehnal/LiteMol#20]
I was using up to recently v1.0, but now with the changes you made for me I've switched to the master. I'm not sure if this is an issue for you, but I thought that you might have come across this. I'm using the viewer with Angular(2/4). 

This is my class: 
```
import {Component, Input, OnChanges, OnInit, SimpleChanges} from '@angular/core';

import LiteMol from 'litemol'
import {environment} from '../../../../../../environments/environment';

const baseURL = environment.pdb_base_url;

@Component({
  selector: 'cp-litmol-viewer',
  templateUrl: 'litmol-viewer.component.html',
  styleUrls: ['litmol-viewer.component.css']
})
export class LitmolViewerComponent implements OnInit, OnChanges {
  private _plugin: any;
  private _selectedXRef: string;

  constructor() {
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (this._plugin) {
      if (changes['selectedXRef']) {
        this.loadMolecule();
      }
    }
  }

  ngOnInit() {
    this._plugin = LiteMol.Plugin.create({
      target: '#litemol',
      viewportBackground: '#fbfbfb',
      layoutState: {
        hideControls: true,
        isExpanded: false
      },
      // Knowing how often and how people use LiteMol
      // gives us the motivation and data to futher improve it.
      //
      // This option is OFF by default!
      allowAnalytics: true
    });
    this.loadMolecule();
  }

  loadMolecule(): void {
    this.plugin.clear();
    this._plugin.loadMolecule({
      id: this._selectedXRef,
      url: baseURL + '/static/entry/' + this._selectedXRef.toLowerCase() + '_updated.cif',
      format: 'cif' // default
    });
  }

  get plugin(): any {
    return this._plugin;
  }

  get selectedXRef(): string {
    return this._selectedXRef;
  }

  @Input()
  set selectedXRef(value: string) {
    this._selectedXRef = value;
  }
}
```

For some reason, when I compile it for production I get this error: 
![screen shot 2017-06-27 at 15 25 08](https://user-images.githubusercontent.com/5269116/27592826-5c771ab2-5b4d-11e7-9be4-956b524b1d30.png)

**Comment by tschaka1904** [comment]
I was thinking that I might be some `tree shaking` issue, as it seem to work in `dev mode`. Basically when I start `bundling` it is doing this. Version `1.0` didn't have this issue.

**Comment by dsehnal** [comment]
This seems like a react related issue. By any chance, is the angular bundler using "amd" modules?

**Comment by tschaka1904** [comment]
This is possible yes. How does that influence it?

**Comment by tschaka1904** [comment]
I just confirmed, no problem with v1.0 but with the master.

**Comment by dsehnal** [comment]
Well, I have no idea what's going on. I tried updating to the latest version of React and change events on elements just stopped working... I will investigate more.

**Comment by tschaka1904** [comment]
I see! Let me know if there is anything I can help with.

**Comment by dsehnal** [comment]
I've updated to the latest version of React. Let's see if that fixes it.

**Comment by tschaka1904** [comment]
Super! Thanks! It works: http://www.ebi.ac.uk/complexportal/complex/EBI-9008420

**Comment by dsehnal** [comment]
Great. Small feedback: you might want to indicate which structure is displayed in the 3D view, for example by coloring the background of the row, or just making the text bold.

**Comment by dsehnal** [comment]
And one more: might better to use this color theme for the plugin: https://github.com/dsehnal/LiteMol/blob/master/dist/css/LiteMol-plugin-light.min.css

**Comment by tschaka1904** [comment]
Thanks for the feedback! Much appreciated! 👍 We're currently working on the highlighting.

**Comment by shinde-ha** [comment]
Hi,
I'm a beginner using Litemol in an angular application as presented in the question above and the rest from FAQ documentation. I am not able to render the css and font in chromium. Do I need to explictly refer those while bundling?
@tschaka1904 can you share the code base for html or ts module please? That will help me knowing where I'm lacking here.
Thanks!
