### ISSUE TITLE
Rotation state not preserved after visualization style update when only one entity is present.

### ISSUE THREAD

**Issue by davidjakubec** [dsehnal/LiteMol#21]
Hi,

I noticed that when there is only one molecular entity* present in the structure, then when one rotates or zooms in on the structure, and then changes the visualization type (for example, from cartoon to balls and sticks), then the rotation and zoom state of the plugin resets. Not sure if this is intended behaviour, but it doesn't behave like this when multiple entities are present.

Cheers,
David

----------
*by "molecular entity" I mean each "selection" for which the visualization type can be set separately, for example, when one loads te structure 9ant, "entities" are going to be "all residues", "interacting residues", "ligands", "unbound water". If one removes any three of these, then the the issue described above is observed for the remaining one.

**Comment by dsehnal** [comment]
Hi,

This is "by design" (as in I know why it's happening). I will try to do fix it next week.

Thanks,
David

**Comment by davidjakubec** [comment]
Thank you. Preserving the rotation state is really useful when one has the view focused on, for example, active site, and wants to take multiple screenshots of it using different visualization types.

**Comment by dsehnal** [comment]
This should not be fixed.
