### ISSUE TITLE
react

### ISSUE THREAD

**Issue by andreassteffen** [dsehnal/LiteMol#24]
Hi,
this looks great! Are you planning to provide a react component for the viewer?
thanks - A.

**Comment by dsehnal** [comment]
Hi, glad you like it :)

The UI is currently written in React using a separate "private instance" that needs to be rendered in a DIV (or equivalent container) with absolute or relative position.

It is trivial to wrap the plugin inside a React component, see for example https://github.com/MolQL/molql/blob/99e7ee60a6396c987d46f282a00162118d68920d/src/molql-explorer/ui.tsx#L110 . After you do this, it is possible to control the plugin with the same code as present in the [examples](https://github.com/dsehnal/LiteMol/tree/master/examples) or just browse around the MolQL thing to see how it's used.

I understand that by "proving a React component" you probably meant something that allows ``<LiteMol loadPDB='1tqn'>``. This is indeed not currently available, but it is easy to write this logic yourself. If you need help with that, please just ask. I will keep in mind including a React component for the next release sometimes next year.

David

**Comment by andreassteffen** [comment]
great. Yes that's what I was thinking about. I will test it!
