### ISSUE TITLE
2TAA - something is wrong with transformation matrices

### ISSUE THREAD

**Issue by wojdyr** [dsehnal/LiteMol#25]
When I open the 2TAA entry on https://webchemdev.ncbr.muni.cz/LiteMol/Viewer/ I see overlapping molecules:
![litemol_screenshot](https://user-images.githubusercontent.com/491873/35064486-2089205c-fbc2-11e7-990e-ba078440225d.png)
(blue and beige molecules are overlapping in the center of this picture)

This entry is quite peculiar, I was checking how different viewers are displaying it.

**Comment by dsehnal** [comment]
So how do other viewers display it?

**Comment by dsehnal** [comment]
I have just checked it and its an error directly in the coordinates of the input file. If you want to see just the individual asymmetric units, click on the morel entry and “create assembly”.

**Comment by wojdyr** [comment]
> So how do other viewers display it?

Not very well: https://github.com/pemsley/coot/issues/17

This entry has unusual SCALE record (_atom_sites.fract_transf_* in mmCIF).

**Comment by dsehnal** [comment]
So do you know how to fix it? Maybe it's a problem with the software that generated the entry?

**Comment by wojdyr** [comment]
Yes, the file is wrong. Sorry for the noise.
