### ISSUE TITLE
Support for (old) 80 character PDB files?

### ISSUE THREAD

**Issue by sillitoe** [dsehnal/LiteMol#3]
The [80 character PDB format](http://deposit.rcsb.org/adit/docs/pdb_atom_format.html) is officially deprecated, but lots of applications still use it (and probably will do for some time).

I can't see any obvious mention of a parser for this old format (e.g. ```ATOM``` records), but it would be really useful.

**Comment by dsehnal** [comment]
There is a partial support for the PDB format (parses ATOM, HETATM, symmetry).  You just have to specify ``format`` parameter in ``CreateFromData`` transform.

```TypeScript
action.add(a, Transformer.Data.Download, { url: `https://www.ebi.ac.uk/pdbe/entry-files/pdb${id}.ent`, type: 'String', id })
  .then(Transformer.Molecule.CreateFromData, 
     { format: LiteMol.Core.Formats.Molecule.SupportedFormats.PDB }, { })
  .then(Transformer.Molecule.CreateModel, { modelIndex: 0 })
  // ...
 })
```

For full example please see the CustomDensity example ( https://github.com/dsehnal/LiteMol/blob/master/examples/CustomDensity/src/Data.ts)

Secondary structure detection for PDB files is on a short term TODO list. If you need it now, I can add it sooner than later.

If you need more help, please ask.

**Comment by sillitoe** [comment]
Excellent, thanks.

If automatic secondary structure detection is required for accurate representation of cartoon then I guess it would be useful.

I'll close this ticket though
