### ISSUE TITLE
Carbohydrates - Update visual toolbar - VDW option error

### ISSUE THREAD

**Issue by mandarsd** [dsehnal/LiteMol#32]
VDW toggle throws error in update visual toolbar for Carbohydrates visual

![litemol_error](https://user-images.githubusercontent.com/12937838/40774531-be059de2-64bd-11e8-894e-06e0300982bd.png)

**Comment by dsehnal** [comment]
It should now be fixed.

**Comment by mandarsd** [comment]
Excellent! Working fine now.
