### ISSUE TITLE
LiteMol in mpn package manager

### ISSUE THREAD

**Issue by skodapetr** [dsehnal/LiteMol#37]
As of now it seems that the "core" LiteMol is not in the npm package manager. 
There are only two packages that wraps LiteMol in some way, however I think it would be useful to provide LiteMol as it is.

Is there any chance that LiteMol will make it to the npm package manager?

**Comment by dsehnal** [comment]
In package.json you can use a GitHub repo as a source like ``"litemol": "github:dsehnal/LiteMol"`` or (``"litemol": "github:dsehnal/LiteMol#commithash"``). I've used it in https://github.com/MolQL/molql and it worked fine.

Would this be enough for your use case?

**Comment by skodapetr** [comment]
Sure, that is good enough.

I was just wondering if there was a reason, besides a lack of resources (time :),  why the project is missing from npm as it can be considered to be a "standard way" of distribution.

**Comment by kiyoko** [comment]
I also would like to see litemol in npm because I'd like to use litemol as a BioJS web component.

**Comment by dsehnal** [comment]
Ok I will have a look into it.

**Comment by dsehnal** [comment]
Thanks for the patience, it's now available as 'litemol' package.
