### ISSUE TITLE
What if I want to highlight an amino acid in a 3D structure?

### ISSUE THREAD

**Issue by Lukezain** [dsehnal/LiteMol#38]
I want to control, when I click on the name of an amino acid in a drop-down list, it highlights the amino acid on the 3D structure.

**Comment by dsehnal** [comment]
It is shown how to highlight/select a given residue for example in the Commands [ [source](https://github.com/dsehnal/LiteMol/tree/master/examples/Commands) | [view live](https://webchemdev.ncbr.muni.cz/LiteMol/Examples/Commands) ] example.

Do the residues come from an outside list or do you need a list from the structure itself?

**Comment by Lukezain** [comment]
Thank you for your replay, I think I found a solution.
