### ISSUE TITLE
I have two pdb files locally. I want to implement two views superimposed together.

### ISSUE THREAD

**Issue by ye1002551506** [dsehnal/LiteMol#40]
How to use code to achieve?

**Comment by dsehnal** [comment]
There is an example for basic superposition: `Transforms` [ [source](https://github.com/dsehnal/LiteMol/tree/master/examples/Transforms) | [view live](https://webchemdev.ncbr.muni.cz/LiteMol/Examples/Transforms) ]

However, the superposition algorithm only works on structures with the same or very similar sequence. If you want a proper superposition algorithm, you will have to get it from somewhere else. However, if you know the transformation that superposes the structures, you can just apply that.

**Comment by ye1002551506** [comment]
First of all, thank you for your generous answer. I wish I could describe my problem in more detail in order to get more accurate advice.

I have two PDB files, but the source-url attribute in index. html allows only one file to be passed in. I want to achieve the effect can be generated in the http://webchemdev.ncbr.muni.cz/LiteMol/Viewer/ of the viewer, the viewer can be introduced into multiple PDB files, but I don't know how to use the code to achieve the effect?

1. I have two PDB files. Can I achieve the desired effect by modifying the attributes of db-lite-mol in index. html ?

2. If modifying index. html cannot achieve the desired effect, what is the easiest way to solve the problem?  
Thank you in advance @dsehnal

**Comment by dsehnal** [comment]
Yes, the angular wrapper does not seem to support multiple files at once.

But you should be able to replace that with the `SimpleController` [ [source](https://github.com/dsehnal/LiteMol/tree/master/examples/SimpleController) | [view live](https://webchemdev.ncbr.muni.cz/LiteMol/Examples/SimpleController) ] quite easily.

You should be able to take the JavaScript code from here https://webchemdev.ncbr.muni.cz/LiteMol/Examples/SimpleController/LiteMol-example.js and simply call ``loadMolecule`` twice with different URLs and ``format: 'pdb'``.

**Comment by ye1002551506** [comment]
Thank you for your perfect answer, this has solved my problem perfectly, and I would like to express my heartfelt thanks and respect to you here. @dsehnal

**Comment by dsehnal** [comment]
You're welcome.
