### ISSUE TITLE
Downloading electron density from specific URL

### ISSUE THREAD

**Issue by bartvanb** [dsehnal/LiteMol#44]
Hello,

I would like to show electron density from PDB-REDO in the LiteMol plugin on a website that we are developing, but I don't know how I can specify the URL for that. 
I found in the 'Commands' example that density was loaded by the function `LiteMol.Viewer.PDBe.Data.DownloadDensity()` but this is unsuited for my purpose.

How can I specify the URL? And does it actually download MTZ files or density in another format?

Thanks for your help! I like the plugin a lot!

Bart

**Comment by dsehnal** [comment]
Hi,

if you want to streaming access to the density data that is available at PDBe, it is required to use the [DensityServer](https://github.com/dsehnal/DensityServer). The server requires a precomputing step where you input CCP4 file generated for the entire unit cell.

You can also load CCP4 files directly in LiteMol using these transforms:

- Download (binary data) https://github.com/dsehnal/LiteMol/blob/master/src/lib/Bootstrap/Entity/Transformer/Data.ts#L28
- Parse https://github.com/dsehnal/LiteMol/blob/master/src/lib/Bootstrap/Entity/Transformer/Density.ts#L13
- Static Surface https://github.com/dsehnal/LiteMol/blob/master/src/lib/Bootstrap/Entity/Transformer/Density.ts#L78 for static surface
- Dynamic surface around selection  https://github.com/dsehnal/LiteMol/blob/master/src/lib/Bootstrap/Entity/Transformer/Density.ts#L125

David

**Comment by bartvanb** [comment]
Hi David,

Thanks for the quick reply. Am I correct in assuming the CCP4 files you are mentioning are .map files?
I'll look into the suggested solutions.

Bart

**Comment by dsehnal** [comment]
Yes, it's the MAP format.

**Comment by bartvanb** [comment]
Hi David,

We have by now set up a service to get ccp4 maps from PDB-REDO data. One can retrieve e.g. https://pdb-redo.eu/map-maker/map?id=1cbs&stage=final&type=density&sampling-rate=1.5.

I tried using this to show electron density in the following way:
```
var loadMap = function (id) {
    var action = Transform.build()
        .add(plugin.context.tree.root, Transformer.Data.Download, { url: "https://pdb-redo.eu/map-maker/map?id=" + id + "&stage=final&type=density&sampling-rate=1.5", type: 'binary', id: id })
        .then(Transformer.Density.CreateVisual, { style: Visualization.Density.Style });
}

loadMap('1c7h');
```

but unfortunately that doesn't work. I haven't been able to figure out how to do it otherwise from the examples, nor do I know if it actually downloads the map (where can I check this?).

Could you suggest how to get this working? 
Also, how should I define ``Visualization.Density.Style``?

Thanks a lot for your help.
Bart

**Comment by dsehnal** [comment]
Hi Bart,

your map works fine.

What you need to do is something along these lines:

```js
var Bootstrap = LiteMol.Bootstrap; // if not specified elsewhere

var loadMap = function (id) {
    var style =  Bootstrap.Visualization.Density.Style.create({
      isoValue: 1.5,
      isoValueType: Bootstrap.Visualization.Density.IsoValueType.Sigma,
      color: LiteMol.Visualization.Color.fromHex(0x3362B2), 
      isWireframe: true,
      transparency: { alpha: 0.75 }
    };
    
    var action = Transform.build()
        .add(plugin.context.tree.root, Transformer.Data.Download, { url: "https://pdb-redo.eu/map-maker/map?id=" + id + "&stage=final&type=density&sampling-rate=1.5", type: 'binary', id: id })
        .then(Transformer.Density.ParseData, { format: LiteMol.Core.Formats.Density.SupportedFormats.CCP4 })
        .then(Transformer.Density.CreateVisual, { style: style });
}
```
Alternatively, have a look at this example: `CustomDensity` [ [source](https://github.com/dsehnal/LiteMol/tree/master/examples/CustomDensity) | [view live](https://webchemdev.ncbr.muni.cz/LiteMol/Examples/CustomDensity) ]

David

**Comment by bartvanb** [comment]
Hi David,

Thanks for another quick and helpful response!

I took the code you provided but unfortunately it does not work yet in the minimal example I have so far (https://www.dropbox.com/s/t3ypxwr51qba18z/lm_redo.zip?dl=0).

I suspect it may have something to do with waiting for the map download. We generate the maps on the fly so it takes a bit of time. In the (extreme) case of a ribosome, getting the map takes about 5-10 if I use wget on unix. However, if I load the litemol plugin, it says the map is loaded almost instantaneously. 
Could this be an issue? Should I include a 'wait' command for getting the map before parsing it?

Thanks

**Comment by dsehnal** [comment]
The waiting is not the issue, the waiting is automatic.

If you open the dev console, is there any message related to the download?

Alternatively, if you show the plugin controls, are the nodes corresponding to the transforms created in the tree?

You should also be able to modify the example I pointed to earlier just by changing the URL in the data.ts file.

I am away from computer now but I will have a closer look at your example later.

**Comment by bartvanb** [comment]
There is no message in the dev console about the density map (there is for the molecule) and I don't see any change in plugin controls with or without density map.

I built the example (works fine) and then changed the URL: then it doesn't work. So I guess the problem is in getting the map file. Maybe the important difference is that you download the map at http://blabla/xxx.ccp4 while we have the link https://pdb-redo.eu/map-maker/map?id=1cbs&stage=final&type=density&sampling-rate=1.5 which generates a file that doesn't necessarily have the name xxx.ccp4. Could that be correct?

Thanks a lot for your help, absolutely no worries about looking later.

**Comment by dsehnal** [comment]
The map is downloaded just fine and can be displayed at https://v.litemol.org if you use the download data option, use the example url you provided earlier, parse ccp4 and create the visual.

So perhaps some issues with your server settings?

**Comment by bartvanb** [comment]
The CustomDensity example with modified URL now works. The issue is that we calculated the map close to the origin whereas the protein used in the example had coordinates far away from there so I simply missed it...
So we will change the map calculation to match the protein coordinates. You could consider adding support for symmetry in ccp4 maps (the info is in there I believe) but I guess that could be a lot of work for limited applicability.

That said, my minimal working example still doesn't work. In contrast to the (modified) example, there is no 'Download electron density' button, but I would expect it to be downloaded+shown automatically there.

I will try now to customize the CustomDensity example further for the focussing on specific residues (which I achieved in the previous example but there density doesn't work yet).

**Comment by dsehnal** [comment]
I would still recommend that you use the DensityServer. It even supports the symmetry in the regard that it can show density around symmetry related copies of the protein. Also the slicing around the protein or its selection is automatic.

In general the symmetry just from the slice provided in the ccp4 file is complicated as the images may overlap and it would generate bad artifacts.

**Comment by bartvanb** [comment]
You're right, I did not consider the artifacts. I'll have a look at the DensityServer too.

**Comment by dsehnal** [comment]
Also with the DensityServer, you can take the data directly from PDBe and don’t have to do any work yourself. It’s the “streaming access” to the PDBe’s EDS https://www.ebi.ac.uk/pdbe/densities/ .

**Comment by bartvanb** [comment]
But that we specifically do not want to do: we want to show PDB-REDO map+model which is different from the PDB data. Can we also visualize that with DensityServer?

**Comment by dsehnal** [comment]
Yes, you just need to run the preprocessing step on your ccp4 files generated for the whole unit cell.

**Comment by bartvanb** [comment]
Hi David,

We updated our service to generate ccp4 map files to fit to the protein coordinates. This works well with a modified CustomDensity example that I made.
Now I am trying to integrate the working density example into my 'master' LiteMol-script that already does the other things I want done (e.g. focus on a specific residue).

I think that I am almost there but compared to the example, there are no buttons that could be clicked to load the map. I noticed in the compiled Javascript that a function applyDownload() is called in the CustomDensity example to finally show the map and I guess something like this is needed.

Could you have a quick look at my current state of things and advise me how to proceed? I would be very grateful. My code can be found at https://www.dropbox.com/s/t3ypxwr51qba18z/lm_redo.zip?dl=0.

Cheers, Bart

**Comment by dsehnal** [comment]
Hi Bart,

you are missing ``plugin.applyTransform(action)`` in your ``loadMap`` function.

David

**Comment by bartvanb** [comment]
Yes that does the trick. Thanks a lot for all the help David!
