### ISSUE TITLE
question on selecting residue

### ISSUE THREAD

**Issue by bartvanb** [dsehnal/LiteMol#46]
Hi David,

My LiteMol plugin centers on a specific residue which I would like to emphasize. At present, upon opening the window, the residue is shown as 'Cartoon' just as all the other residues. Once a residue is clicked, LiteMol shows a more detailed view of the residue (ball and stick). 
Without someone clicking on the residue, can we move directly to the more detailed view (as if someone had clicked the residue upon opening the window)?

Bonus question: how can I set the depth fog (stronger/weaker)?

Thanks,
Bart

**Comment by dsehnal** [comment]
Hi Bart,

the `Commands` [ [source](https://github.com/dsehnal/LiteMol/tree/master/examples/Commands) | [view live](https://webchemdev.ncbr.muni.cz/LiteMol/Examples/Commands) ]  example shows how to focus a residue and create a custom representation for it.

Alternatively, use this command https://github.com/dsehnal/LiteMol/blob/master/src/lib/Bootstrap/Event/Commands.ts#L36 with an appropriate query (here is an example usage https://github.com/dsehnal/LiteMol/blob/85ec87c2698b6abeca8a18cf150f0341b8f2c6ea/src/Viewer/App/Examples.ts#L213 ).

The fog can't really be controlled easily in code now as the behavior is built into the mouse event handlers on the viewport. But if this could be an essential feature, I guess I could do something about it.

David

**Comment by bartvanb** [comment]
Thanks David, the second option was exactly what I wanted and it's working perfectly :)
