### ISSUE TITLE
Density maps (from PDB-REDO) do not work for all entries

### ISSUE THREAD

**Issue by bartvanb** [dsehnal/LiteMol#48]
Hi David,

As you are aware, I have been creating a LiteMol plugin to display a specific residue in PDB-REDO structures and maps. A working example is found here:
https://lahma.rhpc.nki.nl/litemol?&pdbid=1cbs&chain=A&resnum=15
Any other pdb entry, chain, or residue can be focused on by changing the respective parameters.

While testing I came across a few structure models where the maps do not load, e.g.:
https://lahma.rhpc.nki.nl/litemol?&pdbid=1c7h&chain=A&resnum=15

The maps load normally into Coot. Also, the map is defined in the protein area and not near the origin so displacement effects should not be a factor.
Could you offer a suggestion why this may be? 

PS: from the working example you may see why we would like to play with the fog depth. If you have the time, this would be a cool feature for us but we are already quite satisfied with the current version.

Cheers,
Bart

**Comment by dsehnal** [comment]
Hi Bart,

your volume file for 1c7h seems to have something wrong about it (perhaps something in the header -- I did not investigate the details; and Coot is perhaps more "forgiving" than the LiteMol parser). I was able to load the density data for 1c7h using the DensityServer in LiteMol just fine (and the original input was generated using fft for the whole unit cell from the reflection data [cant remember the file format extension]). So could  you please double check the header & data for this file are really ok?

Fog: OK, I might have a look :)

Regards,
David

**Comment by bartvanb** [comment]
Alright, I'll get back to you, probably a few days from now.

**Comment by dsehnal** [comment]
You can now change "fog factor" like this https://github.com/dsehnal/LiteMol/blob/master/examples/Commands/src/App.ts#L172

Setting it to say 0.5 should give you the results you want.

You might also want to bind the "ResetScene" command (Bootstrap.Command.Visual.ResetScene) where you set the fogFactor to 1.

David

**Comment by bartvanb** [comment]
Hi David,
Thanks for adapting the fog factor, it looks even better now!
As for the not-working map file for 1c7h, could you indicate where in the code you parse the map files? Then we can have a look here why the 1c7h file is not parsed as most others.
Thanks,
Bart

**Comment by dsehnal** [comment]
The code is here https://github.com/dsehnal/LiteMol/blob/master/src/lib/Core/Formats/Density/CCP4.ts

David

**Comment by bartvanb** [comment]
As far as we can see, our version of the 1c7h map file is successfully parsed. Various data are extracted from the map file and there are also no error messages. Could it also go wrong further down the line?
Bart

**Comment by dsehnal** [comment]
Ok I will have a look.

**Comment by dsehnal** [comment]
Your file seems to have incorrectly generated header.

This is what you store in the header:

```
max: 1.1754943508222875e-38
min: 3.4028234663852886e+38
mean: NaN
```

The mean value is used to compute standard deviation from the data and because it is NaN the whole thing breaks down.

It is possible that coot computes the min/max/mean directly from the data.

---------

If I open 1c7h from http://www.ebi.ac.uk/pdbe/coordinates/files/1c7h.ccp4 I get

```
max: 1.8442473411560059
mean: 0.00029255085974000394
min: -0.9640383720397949
```

David

**Comment by bartvanb** [comment]
Thanks David, that solved it
