### ISSUE TITLE
Serialize/restore camera state for persisted scene

### ISSUE THREAD

**Issue by suyang-nju** [dsehnal/LiteMol#51]
I can get the camera state by subscribing to `Event.Visual.CameraChanged` event. How do I serialize the camera state and restore it to the scene later? Basically, I'd like to persist the scene across user sessions.

**Comment by dsehnal** [comment]
This should be possible by using ``plugin.context.scene.scene.camera.snapshot/restore`` functions (https://github.com/dsehnal/LiteMol/blob/master/src/lib/Visualization/Base/Camera.ts#L237).

**Comment by suyang-nju** [comment]
Thank you!
