### ISSUE TITLE
Show/hide viewport controls (toolbar)

### ISSUE THREAD

**Issue by suyang-nju** [dsehnal/LiteMol#53]
Is there a way in LiteMol to show/hide/toggle the floating toolbar (CSS class `lm-viewport-controls`) and/or individual buttons therein? Should I just use CSS to do that?

**Comment by dsehnal** [comment]
I think you best hack it with CSS. Other methods would be too complicated I think.

**Comment by suyang-nju** [comment]
OK. Thanks!
