### ISSUE TITLE
3D-SNFG with GLYCAM residue naming

### ISSUE THREAD

**Issue by Dave-Montgomery** [dsehnal/LiteMol#54]
When loading in a molecule with GLYCAM residue naming instead of common residue naming, 3D-SNFG does not work. I've attached two files of mannose, one with common naming:
[MAN.pdb.gz](https://github.com/dsehnal/LiteMol/files/3423068/MAN.pdb.gz)
and one with GLYCAM naming:
[0MA.pdb.gz](https://github.com/dsehnal/LiteMol/files/3423069/0MA.pdb.gz)
When loaded into the LiteMol viewer (https://www.litemol.org/Viewer/) you can see that only one will display 3D-SNFG. I see in the LiteMol-viewer.js that the GLYCAM naming is listed, but this doesn't seem to make it to the viewer.

**Comment by dsehnal** [comment]
Sorry for the late reply. The GLYCAM names are currently disabled because there were some conflicts with the "common" naming. Do you need to support different namings in a single LiteMol instance or is it enough if there is a global constant that you change once when the plugin is loaded?

**Comment by Dave-Montgomery** [comment]
I think I figured it out; I uncommented line 1971, 
for (const name of instance.glycam.names) entry(name, instance.glycam);
and it worked
