### ISSUE TITLE
Rotate control fails & defaults to Zoom

### ISSUE THREAD

**Issue by GilMar-TriFold** [dsehnal/LiteMol#62]
After using LiteMol browser plugin (Firefox 66.0.3 on Ubuntu 14.04 but also encountered on Chromium) the rotate control (left mouse button) fails & all I get is zoom in/out.

Can only fix by reloading the page & re-opening the CIF file.

**Comment by dsehnal** [comment]
I am sorry but I can't reproduce this in neither chrome or firefox (not on Linux, but still).

Does this happen in Mol* https://molstar.org/viewer/ as well?

Btw. latest version of Firefox is 80, upgrading might work.

**Comment by GilMar-TriFold** [comment]
It does not seem to happen on Mol* (I am new to this, teaching myself some basic BioChemistry).  I am struggling to reproduce the issue myself at the moment.  Will hopefully upgrade Ubuntu soon as it (& the libs) is old.  Will try later Firefox but may switch to Mol* also.  I will close this unless I can get a reproduce-able sequence of steps.

**Comment by dsehnal** [comment]
Mol* superseeds LiteMol, so any fixes would happen there anyway.
