### ISSUE TITLE
3d molecules missing beta-sheets structures

### ISSUE THREAD

**Issue by mb925** [dsehnal/LiteMol#65]
Hi!

several PDB molecules are only showing some beta-sheets in the 3D structure, but not all. I know there are more beta-sheets because I saw them in pymol. An example is PDB molecule 4r37B.

Why is that? Can I set some configuration to make Litemol more sensible to secondary structure detection?

Thank you for your help.

Martina

**Comment by dsehnal** [comment]
Hi,

Yep, 4r37 secondary structure isn't computed very well in LiteMol. However, Mol* https://molstar.org/ does render it correctly (or at least better I guess). Would it be an option for you to switch to that viewer? The usage is quite similar to how LiteMol works.

![image](https://user-images.githubusercontent.com/21145776/105185881-5dca5b80-5b31-11eb-84f5-cd89a7a767c5.png)


David

**Comment by mb925** [comment]
Thank you, I'll evaluate to switch to Mol* in the future.
