### ISSUE TITLE
"Error (Visual (Polymer)): Cartoons cannot be constructred from this model/selection." occurs

### ISSUE THREAD

**Issue by nkimura-noguchi** [dsehnal/LiteMol#68]
LiteMol doesn't work and occurs an error in below code:

**HTML**
```
<div id="molecule_data_3d_image" class="w-50 mx-3"></div>
<textarea id="mol01_mol3d" name="mol01_mol3d" disabled="">ATOM      1 6C11  PA A   1      37.997  35.950   5.994  1.00  0.00           C 
ATOM      2 H16R  PA A   1      38.913  36.357   6.424  1.00  0.00           H 
ATOM      3 H16S  PA A   1      37.510  36.817   5.544  1.00  0.00           H ENDMDL</textarea>
```

**JavaScript**
```
jQuery(function($) {
    create3dMolecule('#molecule_data_3d_image');
    loadMolecule($, $('#mol01_mol3d').val());
});

function create3dMolecule(target) {
    mol3d = LiteMol.Plugin.create({
        target: target,
        viewportBackground: '#fff',
        layoutState: {
            hideControls: true,
        },
    })
}

function loadMolecule($, mol3dString) {
   mol3d.clear();
   mol3d.loadMolecule({
       format: 'pdb',
       data: mol3dString,
   });
}
```

**Occurred error and warning**
```
14:22:23
Create Molecule (String Data) finished in 134ms.
14:22:23
Error (Visual (Polymer)): Cartoons cannot be constructred from this model/selection.
14:22:23
Warning (Create Selection (Model 1)): Empty selection (HET).
14:22:23
Warning (Create Selection (Model 1)): Empty selection (Water).
```

I don't know why it doesn't work. I tried in below code. It works.

**HTML**
```
<textarea id="mol01_mol3d" name="mol01_mol3d" disabled="">ATOM      1  N   ALA A  18     -47.031  22.548  18.482  1.00112.51           N  
ATOM      2  CA  ALA A  18     -47.456  22.679  19.873  1.00137.48           C  
ATOM      3  C   ALA A  18     -46.778  23.858  20.572  1.00147.87           C  
ATOM      4  O   ALA A  18     -46.631  23.830  21.790  1.00143.56           O  ENDMDL</textarea>
```

I would like to ask your advice on this matter.

**Comment by dsehnal** [comment]
You are getting this because 1 residue is not enough to construct the cartoons representation in LiteMol. There is a way to go around this by creating the representation by hand, but it's probably better to give [Mol*](https://molstar.org) a try which should resolve this issue automatically.

**Comment by nkimura-noguchi** [comment]
> You are getting this because 1 residue is not enough to construct the cartoons representation in LiteMol. There is a way to go around this by creating the representation by hand, but it's probably better to give [Mol*](https://molstar.org) a try which should resolve this issue automatically.

Thanks for replying. Can I run Molstar not using node.js?  If it  can do, I would like to know how to use it. Also is there documentation of Molstar for developer? I would like to use it like functions of create3dMolecule(target) and loadMolecule($, mol3dString) that I defined .

**Comment by dsehnal** [comment]
There is https://molstar.org/docs/plugin/#viewer-wrapper (still heavily under construction).

You don't need nodejs to run it in browser However, you need it to compile it.

**Comment by nkimura-noguchi** [comment]
Thanks for teaching me about them. Molstar works completely in my environment now. It's very cool and useful!
