### ISSUE TITLE
LiteMol showing up blank on some OS/Browsers

### ISSUE THREAD

**Issue by gitoliver** [dsehnal/LiteMol#78]
We have LiteMol embedded in our webpage and have some problems popping up in the last week.

One user on Mac reported that the molecule isn't showing. Here is an example on Mac with the latest Chrome (101.0.4951.41). Giving the same inputs on the same machine, but in Safari, works fine. This is a repeatable bug, and clearing the cache/rebooting/praying doesn't effect it.
![image](https://user-images.githubusercontent.com/17079588/166419145-163ff779-808f-4a90-a496-173215d5a5a4.png)

Note you can get directly to the page with this link: http://glycam.org/url/condensed/DManpa1-6DManpa1-3DManpb1-4DGlcpNAcb1-4DGlcpNAcb1-OH

Last week another user running on Windows in Firefox (100.0b9 Developer Ed) was getting a black screen for litemol. Might be a different bug or related. Tried private window (incognito) with disabled extensions too. Same result. Structure works fine in Edge on the same machine. I installed the latest Firefox developer edition on Ubuntu 20.04 LTS but could not reproduce the bug.
![image](https://user-images.githubusercontent.com/17079588/166419205-9d8fefe9-bc0b-4296-a115-285f6d53e570.png)

**Comment by dsehnal** [comment]
Hi Oliver,

I don't think I will be able to fix this bug for you. However, Mol* also supports showing of the special symbols for sugars and if you are just showing pdb files it should be a drop in replacement. Could you try on molstar.org if the files you are interested in open correctly and I could perhaps help you with integrating that.

**Comment by gitoliver** [comment]
Hi David,

Yes the plan is to move to Mol* eventually, it's just that while LiteMol is still working there are other things that take priority. This bug isn't reproducible on other machines, seems to be browser/machine specific. I'll pass the info along that we need to try the upgrade to Mol*.
